### ISSUE TITLE
Exception on CentOS 6.5

### ISSUE THREAD

**Issue by DamianZaremba** [seveas/yum_plugin_puppet#5]
[root@testing-05 ~]# cat /etc/redhat-release 
CentOS release 6.5 (Final)

[root@testing-05 ~]# rpm -qa yum
yum-3.2.29-43.el6.centos.noarch

Running puppet produces:

``` python
Error: Could not prefetch package provider 'yum': Execution of '/usr/bin/python /usr/lib/ruby/site_ruby/1.8/puppet/provider/package/yumhelper.py' returned 1: Loading "fastestmirror" plugin
Traceback (most recent call last):
  File "/usr/lib/ruby/site_ruby/1.8/puppet/provider/package/yumhelper.py", line 115, in <module>
    ypl = pkg_lists(my)
  File "/usr/lib/ruby/site_ruby/1.8/puppet/provider/package/yumhelper.py", line 32, in pkg_lists
    my.doConfigSetup()
  File "/usr/lib/python2.6/site-packages/yum/__init__.py", line 248, in doConfigSetup
    return self.conf
  File "/usr/lib/python2.6/site-packages/yum/__init__.py", line 891, in <lambda>
    conf = property(fget=lambda self: self._getConfig(),
  File "/usr/lib/python2.6/site-packages/yum/__init__.py", line 334, in _getConfig
    startupconf.pluginconfpath,disabled_plugins,enabled_plugins)
  File "/usr/lib/python2.6/site-packages/yum/__init__.py", line 546, in doPluginSetup
    plugin_types, confpath, disabled_plugins, enabled_plugins)
  File "/usr/lib/python2.6/site-packages/yum/plugins.py", line 159, in __init__
    self._importplugins(types)
  File "/usr/lib/python2.6/site-packages/yum/plugins.py", line 203, in _importplugins
    self._loadplugin(modulefile, types)
  File "/usr/lib/python2.6/site-packages/yum/plugins.py", line 265, in _loadplugin
    module = imp.load_module(modname, fp, pathname, description)
  File "/usr/lib/yum-plugins/puppet.py", line 17, in <module>
    from yumcommands import YumCommand, checkRootUID, checkGPGKey, checkPackageArg
ImportError: No module named yumcommands
```

Running yum with the plugin installed produces:

``` python
[root@testing-05 ~]# yum update
Loading "fastestmirror" plugin
Loading "puppet" plugin
Running "config" handler for "puppet" plugin
Looking at puppet catalog for repo info
Traceback (most recent call last):
  File "/usr/bin/yum", line 29, in <module>
    yummain.user_main(sys.argv[1:], exit_code=True)
  File "/usr/share/yum-cli/yummain.py", line 285, in user_main
    errcode = main(args)
  File "/usr/share/yum-cli/yummain.py", line 105, in main
    base.getOptionsConfig(args)
  File "/usr/share/yum-cli/cli.py", line 228, in getOptionsConfig
    self.conf
  File "/usr/lib/python2.6/site-packages/yum/__init__.py", line 891, in <lambda>
    conf = property(fget=lambda self: self._getConfig(),
  File "/usr/lib/python2.6/site-packages/yum/__init__.py", line 334, in _getConfig
    startupconf.pluginconfpath,disabled_plugins,enabled_plugins)
  File "/usr/lib/python2.6/site-packages/yum/__init__.py", line 546, in doPluginSetup
    plugin_types, confpath, disabled_plugins, enabled_plugins)
  File "/usr/lib/python2.6/site-packages/yum/plugins.py", line 167, in __init__
    self.run('config')
  File "/usr/lib/python2.6/site-packages/yum/plugins.py", line 184, in run
    func(conduitcls(self, self.base, conf, **kwargs))
  File "/usr/lib/yum-plugins/puppet.py", line 71, in config_hook
    puppet_packages[resource['title']] = resource['parameters'].get('ensure', 'installed')
KeyError: 'parameters'
```

Looking at the value of resource, most entries have a parameters key however some don't such as:

```
{u'title': u'sysstat', u'tags': [u'nrpe', u'rc', u'plugin', u'node', u'default', u'package', u'sysstat', u'check_sar_perf', u'base', u'rc::monitoring', u'nrpe::plugin::check_sar_perf', u'rc::base', u'monitoring', u'class'], u'exported': False, u'file': u'/etc/puppet/environments/production/modules/nrpe/manifests/plugin/check_sar_perf.pp', u'line': 8, u'type': u'Package'}
```

**Comment by seveas** [comment]
Hi Damian,

Sorry for responding ridiculously late, I didn't notice tht you filed this issue!

As for the first one: you have 'yum' as package provider in puppet, this should be 'yum3' as specified in the usage instructions.

And the second one is really an issue in your recipe I think. You haven't set any 'ensure' parameter, which you really should or else the definition is quite useless.
